// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message_test.proto

package encode_decode

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type VarintsA struct {
	A                    int32    `protobuf:"varint,1,opt,name=a,proto3" json:"a,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VarintsA) Reset()         { *m = VarintsA{} }
func (m *VarintsA) String() string { return proto.CompactTextString(m) }
func (*VarintsA) ProtoMessage()    {}
func (*VarintsA) Descriptor() ([]byte, []int) {
	return fileDescriptor_1df2290959daf7b8, []int{0}
}

func (m *VarintsA) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VarintsA.Unmarshal(m, b)
}
func (m *VarintsA) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VarintsA.Marshal(b, m, deterministic)
}
func (m *VarintsA) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VarintsA.Merge(m, src)
}
func (m *VarintsA) XXX_Size() int {
	return xxx_messageInfo_VarintsA.Size(m)
}
func (m *VarintsA) XXX_DiscardUnknown() {
	xxx_messageInfo_VarintsA.DiscardUnknown(m)
}

var xxx_messageInfo_VarintsA proto.InternalMessageInfo

func (m *VarintsA) GetA() int32 {
	if m != nil {
		return m.A
	}
	return 0
}

type ZigZagA struct {
	B                    int32    `protobuf:"zigzag32,1,opt,name=b,proto3" json:"b,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ZigZagA) Reset()         { *m = ZigZagA{} }
func (m *ZigZagA) String() string { return proto.CompactTextString(m) }
func (*ZigZagA) ProtoMessage()    {}
func (*ZigZagA) Descriptor() ([]byte, []int) {
	return fileDescriptor_1df2290959daf7b8, []int{1}
}

func (m *ZigZagA) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ZigZagA.Unmarshal(m, b)
}
func (m *ZigZagA) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ZigZagA.Marshal(b, m, deterministic)
}
func (m *ZigZagA) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ZigZagA.Merge(m, src)
}
func (m *ZigZagA) XXX_Size() int {
	return xxx_messageInfo_ZigZagA.Size(m)
}
func (m *ZigZagA) XXX_DiscardUnknown() {
	xxx_messageInfo_ZigZagA.DiscardUnknown(m)
}

var xxx_messageInfo_ZigZagA proto.InternalMessageInfo

func (m *ZigZagA) GetB() int32 {
	if m != nil {
		return m.B
	}
	return 0
}

type StringA struct {
	A                    string   `protobuf:"bytes,7,opt,name=a,proto3" json:"a,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StringA) Reset()         { *m = StringA{} }
func (m *StringA) String() string { return proto.CompactTextString(m) }
func (*StringA) ProtoMessage()    {}
func (*StringA) Descriptor() ([]byte, []int) {
	return fileDescriptor_1df2290959daf7b8, []int{2}
}

func (m *StringA) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StringA.Unmarshal(m, b)
}
func (m *StringA) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StringA.Marshal(b, m, deterministic)
}
func (m *StringA) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StringA.Merge(m, src)
}
func (m *StringA) XXX_Size() int {
	return xxx_messageInfo_StringA.Size(m)
}
func (m *StringA) XXX_DiscardUnknown() {
	xxx_messageInfo_StringA.DiscardUnknown(m)
}

var xxx_messageInfo_StringA proto.InternalMessageInfo

func (m *StringA) GetA() string {
	if m != nil {
		return m.A
	}
	return ""
}

type EmbeddedA struct {
	A                    *StringA `protobuf:"bytes,7,opt,name=a,proto3" json:"a,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmbeddedA) Reset()         { *m = EmbeddedA{} }
func (m *EmbeddedA) String() string { return proto.CompactTextString(m) }
func (*EmbeddedA) ProtoMessage()    {}
func (*EmbeddedA) Descriptor() ([]byte, []int) {
	return fileDescriptor_1df2290959daf7b8, []int{3}
}

func (m *EmbeddedA) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmbeddedA.Unmarshal(m, b)
}
func (m *EmbeddedA) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmbeddedA.Marshal(b, m, deterministic)
}
func (m *EmbeddedA) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmbeddedA.Merge(m, src)
}
func (m *EmbeddedA) XXX_Size() int {
	return xxx_messageInfo_EmbeddedA.Size(m)
}
func (m *EmbeddedA) XXX_DiscardUnknown() {
	xxx_messageInfo_EmbeddedA.DiscardUnknown(m)
}

var xxx_messageInfo_EmbeddedA proto.InternalMessageInfo

func (m *EmbeddedA) GetA() *StringA {
	if m != nil {
		return m.A
	}
	return nil
}

type ReapeatedA struct {
	A                    []int32  `protobuf:"varint,3,rep,packed,name=a,proto3" json:"a,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReapeatedA) Reset()         { *m = ReapeatedA{} }
func (m *ReapeatedA) String() string { return proto.CompactTextString(m) }
func (*ReapeatedA) ProtoMessage()    {}
func (*ReapeatedA) Descriptor() ([]byte, []int) {
	return fileDescriptor_1df2290959daf7b8, []int{4}
}

func (m *ReapeatedA) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReapeatedA.Unmarshal(m, b)
}
func (m *ReapeatedA) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReapeatedA.Marshal(b, m, deterministic)
}
func (m *ReapeatedA) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReapeatedA.Merge(m, src)
}
func (m *ReapeatedA) XXX_Size() int {
	return xxx_messageInfo_ReapeatedA.Size(m)
}
func (m *ReapeatedA) XXX_DiscardUnknown() {
	xxx_messageInfo_ReapeatedA.DiscardUnknown(m)
}

var xxx_messageInfo_ReapeatedA proto.InternalMessageInfo

func (m *ReapeatedA) GetA() []int32 {
	if m != nil {
		return m.A
	}
	return nil
}

type MultiFieldA struct {
	A                    int32    `protobuf:"varint,1,opt,name=a,proto3" json:"a,omitempty"`
	B                    string   `protobuf:"bytes,7,opt,name=b,proto3" json:"b,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MultiFieldA) Reset()         { *m = MultiFieldA{} }
func (m *MultiFieldA) String() string { return proto.CompactTextString(m) }
func (*MultiFieldA) ProtoMessage()    {}
func (*MultiFieldA) Descriptor() ([]byte, []int) {
	return fileDescriptor_1df2290959daf7b8, []int{5}
}

func (m *MultiFieldA) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MultiFieldA.Unmarshal(m, b)
}
func (m *MultiFieldA) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MultiFieldA.Marshal(b, m, deterministic)
}
func (m *MultiFieldA) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MultiFieldA.Merge(m, src)
}
func (m *MultiFieldA) XXX_Size() int {
	return xxx_messageInfo_MultiFieldA.Size(m)
}
func (m *MultiFieldA) XXX_DiscardUnknown() {
	xxx_messageInfo_MultiFieldA.DiscardUnknown(m)
}

var xxx_messageInfo_MultiFieldA proto.InternalMessageInfo

func (m *MultiFieldA) GetA() int32 {
	if m != nil {
		return m.A
	}
	return 0
}

func (m *MultiFieldA) GetB() string {
	if m != nil {
		return m.B
	}
	return ""
}

type CompareMsg struct {
	Offset               int64        `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit                int64        `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Email                string       `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	D                    *MultiFieldA `protobuf:"bytes,4,opt,name=d,proto3" json:"d,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *CompareMsg) Reset()         { *m = CompareMsg{} }
func (m *CompareMsg) String() string { return proto.CompactTextString(m) }
func (*CompareMsg) ProtoMessage()    {}
func (*CompareMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_1df2290959daf7b8, []int{6}
}

func (m *CompareMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CompareMsg.Unmarshal(m, b)
}
func (m *CompareMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CompareMsg.Marshal(b, m, deterministic)
}
func (m *CompareMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CompareMsg.Merge(m, src)
}
func (m *CompareMsg) XXX_Size() int {
	return xxx_messageInfo_CompareMsg.Size(m)
}
func (m *CompareMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_CompareMsg.DiscardUnknown(m)
}

var xxx_messageInfo_CompareMsg proto.InternalMessageInfo

func (m *CompareMsg) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *CompareMsg) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *CompareMsg) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CompareMsg) GetD() *MultiFieldA {
	if m != nil {
		return m.D
	}
	return nil
}

func init() {
	proto.RegisterType((*VarintsA)(nil), "encode_decode.VarintsA")
	proto.RegisterType((*ZigZagA)(nil), "encode_decode.ZigZagA")
	proto.RegisterType((*StringA)(nil), "encode_decode.StringA")
	proto.RegisterType((*EmbeddedA)(nil), "encode_decode.EmbeddedA")
	proto.RegisterType((*ReapeatedA)(nil), "encode_decode.ReapeatedA")
	proto.RegisterType((*MultiFieldA)(nil), "encode_decode.MultiFieldA")
	proto.RegisterType((*CompareMsg)(nil), "encode_decode.CompareMsg")
}

func init() { proto.RegisterFile("message_test.proto", fileDescriptor_1df2290959daf7b8) }

var fileDescriptor_1df2290959daf7b8 = []byte{
	// 253 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0x41, 0x4b, 0xc3, 0x30,
	0x14, 0xc7, 0x89, 0x75, 0x9b, 0x7b, 0xd3, 0x83, 0x41, 0x66, 0xd8, 0xa9, 0x14, 0x0f, 0xf5, 0x52,
	0x50, 0x3f, 0xc1, 0x10, 0xbd, 0xed, 0x12, 0xc1, 0xc3, 0x2e, 0x23, 0x31, 0x6f, 0x21, 0xd0, 0x34,
	0xa5, 0x79, 0x5e, 0xfc, 0xf4, 0x92, 0xb4, 0x82, 0xdb, 0xa9, 0xfc, 0xdf, 0xbf, 0xbf, 0xf7, 0x7e,
	0x04, 0xb8, 0xc7, 0x18, 0x95, 0xc5, 0x03, 0x61, 0xa4, 0xa6, 0x1f, 0x02, 0x05, 0x7e, 0x83, 0xdd,
	0x57, 0x30, 0x78, 0x30, 0x98, 0x3e, 0x95, 0x80, 0xab, 0x4f, 0x35, 0xb8, 0x8e, 0xe2, 0x96, 0x5f,
	0x03, 0x53, 0x82, 0x95, 0xac, 0x9e, 0x49, 0xa6, 0xaa, 0x7b, 0x58, 0xec, 0x9d, 0xdd, 0x2b, 0x9b,
	0x0b, 0x9d, 0x8b, 0x5b, 0xc9, 0x74, 0x2a, 0x3e, 0x68, 0x70, 0x9d, 0x9d, 0x88, 0x45, 0xc9, 0xea,
	0x65, 0x22, 0x9e, 0x60, 0xf9, 0xe6, 0x35, 0x1a, 0x83, 0x66, 0xcb, 0x1f, 0xfe, 0xaa, 0xd5, 0xf3,
	0xba, 0x39, 0xb9, 0xd9, 0x4c, 0x74, 0x42, 0x36, 0x00, 0x12, 0x55, 0x8f, 0x8a, 0x12, 0x93, 0xd7,
	0x15, 0x65, 0x31, 0x0a, 0x3c, 0xc2, 0x6a, 0xf7, 0xdd, 0x92, 0x7b, 0x77, 0xd8, 0x9a, 0x33, 0xbb,
	0x51, 0x69, 0xba, 0xac, 0xab, 0x1f, 0x80, 0xd7, 0xe0, 0x7b, 0x35, 0xe0, 0x2e, 0x5a, 0xbe, 0x86,
	0x79, 0x38, 0x1e, 0x23, 0x52, 0xfe, 0xbd, 0x90, 0x53, 0xe2, 0x77, 0x30, 0x6b, 0x9d, 0x77, 0x24,
	0x2e, 0xf2, 0x78, 0x0c, 0x69, 0x8a, 0x5e, 0xb9, 0x56, 0x14, 0x79, 0xdb, 0x18, 0x78, 0x0d, 0xcc,
	0x88, 0xcb, 0xac, 0xbf, 0x39, 0xd3, 0xff, 0x27, 0x25, 0x99, 0xd1, 0xf3, 0xfc, 0xae, 0x2f, 0xbf,
	0x01, 0x00, 0x00, 0xff, 0xff, 0x4e, 0x1a, 0x2a, 0x20, 0x6d, 0x01, 0x00, 0x00,
}
